/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ContentPayment {
  export type ContentStruct = {
    contentId: BigNumberish;
    creator: AddressLike;
    title: string;
    contentHash: string;
    price: BigNumberish;
    createdAt: BigNumberish;
    isActive: boolean;
  };

  export type ContentStructOutput = [
    contentId: bigint,
    creator: string,
    title: string,
    contentHash: string,
    price: bigint,
    createdAt: bigint,
    isActive: boolean
  ] & {
    contentId: bigint;
    creator: string;
    title: string;
    contentHash: string;
    price: bigint;
    createdAt: bigint;
    isActive: boolean;
  };
}

export interface ContentPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contents"
      | "createContent"
      | "creatorContents"
      | "deactivateContent"
      | "getContent"
      | "getCreatorContent"
      | "hasAccess"
      | "nextContentId"
      | "purchaseContent"
      | "totalRevenue"
      | "updateContentPrice"
      | "userAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContentCreated"
      | "ContentPurchased"
      | "ContentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createContent",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorContents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorContent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextContentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseContent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateContentPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userAccess",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "contents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorContents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getContent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextContentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userAccess", data: BytesLike): Result;
}

export namespace ContentCreatedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    creator: AddressLike,
    title: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    contentId: bigint,
    creator: string,
    title: string,
    price: bigint
  ];
  export interface OutputObject {
    contentId: bigint;
    creator: string;
    title: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentPurchasedEvent {
  export type InputTuple = [
    contentId: BigNumberish,
    buyer: AddressLike,
    creator: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    contentId: bigint,
    buyer: string,
    creator: string,
    price: bigint
  ];
  export interface OutputObject {
    contentId: bigint;
    buyer: string;
    creator: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentUpdatedEvent {
  export type InputTuple = [contentId: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [contentId: bigint, newPrice: bigint];
  export interface OutputObject {
    contentId: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContentPayment extends BaseContract {
  connect(runner?: ContractRunner | null): ContentPayment;
  waitForDeployment(): Promise<this>;

  interface: ContentPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        contentId: bigint;
        creator: string;
        title: string;
        contentHash: string;
        price: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  createContent: TypedContractMethod<
    [
      _creator: AddressLike,
      _title: string,
      _contentHash: string,
      _price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  creatorContents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateContent: TypedContractMethod<
    [_contentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getContent: TypedContractMethod<
    [_contentId: BigNumberish],
    [ContentPayment.ContentStructOutput],
    "view"
  >;

  getCreatorContent: TypedContractMethod<
    [_creator: AddressLike],
    [bigint[]],
    "view"
  >;

  hasAccess: TypedContractMethod<
    [_user: AddressLike, _contentId: BigNumberish],
    [boolean],
    "view"
  >;

  nextContentId: TypedContractMethod<[], [bigint], "view">;

  purchaseContent: TypedContractMethod<
    [_buyer: AddressLike, _contentId: BigNumberish],
    [void],
    "payable"
  >;

  totalRevenue: TypedContractMethod<[], [bigint], "view">;

  updateContentPrice: TypedContractMethod<
    [_contentId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  userAccess: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        contentId: bigint;
        creator: string;
        title: string;
        contentHash: string;
        price: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createContent"
  ): TypedContractMethod<
    [
      _creator: AddressLike,
      _title: string,
      _contentHash: string,
      _price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorContents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateContent"
  ): TypedContractMethod<[_contentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContent"
  ): TypedContractMethod<
    [_contentId: BigNumberish],
    [ContentPayment.ContentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorContent"
  ): TypedContractMethod<[_creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [_user: AddressLike, _contentId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextContentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseContent"
  ): TypedContractMethod<
    [_buyer: AddressLike, _contentId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateContentPrice"
  ): TypedContractMethod<
    [_contentId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userAccess"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ContentCreated"
  ): TypedContractEvent<
    ContentCreatedEvent.InputTuple,
    ContentCreatedEvent.OutputTuple,
    ContentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContentPurchased"
  ): TypedContractEvent<
    ContentPurchasedEvent.InputTuple,
    ContentPurchasedEvent.OutputTuple,
    ContentPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "ContentUpdated"
  ): TypedContractEvent<
    ContentUpdatedEvent.InputTuple,
    ContentUpdatedEvent.OutputTuple,
    ContentUpdatedEvent.OutputObject
  >;

  filters: {
    "ContentCreated(uint256,address,string,uint256)": TypedContractEvent<
      ContentCreatedEvent.InputTuple,
      ContentCreatedEvent.OutputTuple,
      ContentCreatedEvent.OutputObject
    >;
    ContentCreated: TypedContractEvent<
      ContentCreatedEvent.InputTuple,
      ContentCreatedEvent.OutputTuple,
      ContentCreatedEvent.OutputObject
    >;

    "ContentPurchased(uint256,address,address,uint256)": TypedContractEvent<
      ContentPurchasedEvent.InputTuple,
      ContentPurchasedEvent.OutputTuple,
      ContentPurchasedEvent.OutputObject
    >;
    ContentPurchased: TypedContractEvent<
      ContentPurchasedEvent.InputTuple,
      ContentPurchasedEvent.OutputTuple,
      ContentPurchasedEvent.OutputObject
    >;

    "ContentUpdated(uint256,uint256)": TypedContractEvent<
      ContentUpdatedEvent.InputTuple,
      ContentUpdatedEvent.OutputTuple,
      ContentUpdatedEvent.OutputObject
    >;
    ContentUpdated: TypedContractEvent<
      ContentUpdatedEvent.InputTuple,
      ContentUpdatedEvent.OutputTuple,
      ContentUpdatedEvent.OutputObject
    >;
  };
}
