/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CreatorProfile {
  export type CreatorStruct = {
    username: string;
    bio: string;
    wallet: AddressLike;
    createdAt: BigNumberish;
    isActive: boolean;
  };

  export type CreatorStructOutput = [
    username: string,
    bio: string,
    wallet: string,
    createdAt: bigint,
    isActive: boolean
  ] & {
    username: string;
    bio: string;
    wallet: string;
    createdAt: bigint;
    isActive: boolean;
  };
}

export interface CreatorProfileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "creators"
      | "getCreator"
      | "isCreator"
      | "registerCreator"
      | "totalCreators"
      | "updateCreator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CreatorRegistered" | "CreatorUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "creators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCreator",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCreators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreator",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "creators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCreator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCreator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreator",
    data: BytesLike
  ): Result;
}

export namespace CreatorRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    username: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    username: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    username: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorUpdatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    username: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    username: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    username: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreatorProfile extends BaseContract {
  connect(runner?: ContractRunner | null): CreatorProfile;
  waitForDeployment(): Promise<this>;

  interface: CreatorProfileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  creators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        username: string;
        bio: string;
        wallet: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getCreator: TypedContractMethod<
    [_wallet: AddressLike],
    [CreatorProfile.CreatorStructOutput],
    "view"
  >;

  isCreator: TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;

  registerCreator: TypedContractMethod<
    [_creator: AddressLike, _username: string, _bio: string],
    [void],
    "nonpayable"
  >;

  totalCreators: TypedContractMethod<[], [bigint], "view">;

  updateCreator: TypedContractMethod<
    [_username: string, _bio: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "creators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        username: string;
        bio: string;
        wallet: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreator"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [CreatorProfile.CreatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCreator"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerCreator"
  ): TypedContractMethod<
    [_creator: AddressLike, _username: string, _bio: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCreators"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateCreator"
  ): TypedContractMethod<
    [_username: string, _bio: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CreatorRegistered"
  ): TypedContractEvent<
    CreatorRegisteredEvent.InputTuple,
    CreatorRegisteredEvent.OutputTuple,
    CreatorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CreatorUpdated"
  ): TypedContractEvent<
    CreatorUpdatedEvent.InputTuple,
    CreatorUpdatedEvent.OutputTuple,
    CreatorUpdatedEvent.OutputObject
  >;

  filters: {
    "CreatorRegistered(address,string,uint256)": TypedContractEvent<
      CreatorRegisteredEvent.InputTuple,
      CreatorRegisteredEvent.OutputTuple,
      CreatorRegisteredEvent.OutputObject
    >;
    CreatorRegistered: TypedContractEvent<
      CreatorRegisteredEvent.InputTuple,
      CreatorRegisteredEvent.OutputTuple,
      CreatorRegisteredEvent.OutputObject
    >;

    "CreatorUpdated(address,string,uint256)": TypedContractEvent<
      CreatorUpdatedEvent.InputTuple,
      CreatorUpdatedEvent.OutputTuple,
      CreatorUpdatedEvent.OutputObject
    >;
    CreatorUpdated: TypedContractEvent<
      CreatorUpdatedEvent.InputTuple,
      CreatorUpdatedEvent.OutputTuple,
      CreatorUpdatedEvent.OutputObject
    >;
  };
}
