/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GlamoraHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contentPayment"
      | "createContent"
      | "creatorProfile"
      | "getContractAddresses"
      | "getPlatformStats"
      | "hasAccessToContent"
      | "isCreator"
      | "owner"
      | "platformFee"
      | "purchaseContent"
      | "registerAndCreateContent"
      | "registerCreator"
      | "updatePlatformFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorRegisteredAndContentCreated"
      | "PlatformInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contentPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createContent",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccessToContent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAndCreateContent",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCreator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "contentPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAccessToContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isCreator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAndCreateContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
}

export namespace CreatorRegisteredAndContentCreatedEvent {
  export type InputTuple = [creator: AddressLike, contentId: BigNumberish];
  export type OutputTuple = [creator: string, contentId: bigint];
  export interface OutputObject {
    creator: string;
    contentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformInitializedEvent {
  export type InputTuple = [
    creatorProfileAddress: AddressLike,
    contentPaymentAddress: AddressLike
  ];
  export type OutputTuple = [
    creatorProfileAddress: string,
    contentPaymentAddress: string
  ];
  export interface OutputObject {
    creatorProfileAddress: string;
    contentPaymentAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GlamoraHub extends BaseContract {
  connect(runner?: ContractRunner | null): GlamoraHub;
  waitForDeployment(): Promise<this>;

  interface: GlamoraHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contentPayment: TypedContractMethod<[], [string], "view">;

  createContent: TypedContractMethod<
    [title: string, contentHash: string, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  creatorProfile: TypedContractMethod<[], [string], "view">;

  getContractAddresses: TypedContractMethod<
    [],
    [
      [string, string] & {
        creatorProfileAddr: string;
        contentPaymentAddr: string;
      }
    ],
    "view"
  >;

  getPlatformStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalCreators: bigint;
        totalContent: bigint;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;

  hasAccessToContent: TypedContractMethod<
    [user: AddressLike, contentId: BigNumberish],
    [boolean],
    "view"
  >;

  isCreator: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  purchaseContent: TypedContractMethod<
    [contentId: BigNumberish],
    [void],
    "payable"
  >;

  registerAndCreateContent: TypedContractMethod<
    [
      username: string,
      bio: string,
      title: string,
      contentHash: string,
      price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  registerCreator: TypedContractMethod<
    [username: string, bio: string],
    [void],
    "nonpayable"
  >;

  updatePlatformFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contentPayment"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createContent"
  ): TypedContractMethod<
    [title: string, contentHash: string, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorProfile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContractAddresses"
  ): TypedContractMethod<
    [],
    [
      [string, string] & {
        creatorProfileAddr: string;
        contentPaymentAddr: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalCreators: bigint;
        totalContent: bigint;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAccessToContent"
  ): TypedContractMethod<
    [user: AddressLike, contentId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCreator"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseContent"
  ): TypedContractMethod<[contentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "registerAndCreateContent"
  ): TypedContractMethod<
    [
      username: string,
      bio: string,
      title: string,
      contentHash: string,
      price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerCreator"
  ): TypedContractMethod<[username: string, bio: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CreatorRegisteredAndContentCreated"
  ): TypedContractEvent<
    CreatorRegisteredAndContentCreatedEvent.InputTuple,
    CreatorRegisteredAndContentCreatedEvent.OutputTuple,
    CreatorRegisteredAndContentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformInitialized"
  ): TypedContractEvent<
    PlatformInitializedEvent.InputTuple,
    PlatformInitializedEvent.OutputTuple,
    PlatformInitializedEvent.OutputObject
  >;

  filters: {
    "CreatorRegisteredAndContentCreated(address,uint256)": TypedContractEvent<
      CreatorRegisteredAndContentCreatedEvent.InputTuple,
      CreatorRegisteredAndContentCreatedEvent.OutputTuple,
      CreatorRegisteredAndContentCreatedEvent.OutputObject
    >;
    CreatorRegisteredAndContentCreated: TypedContractEvent<
      CreatorRegisteredAndContentCreatedEvent.InputTuple,
      CreatorRegisteredAndContentCreatedEvent.OutputTuple,
      CreatorRegisteredAndContentCreatedEvent.OutputObject
    >;

    "PlatformInitialized(address,address)": TypedContractEvent<
      PlatformInitializedEvent.InputTuple,
      PlatformInitializedEvent.OutputTuple,
      PlatformInitializedEvent.OutputObject
    >;
    PlatformInitialized: TypedContractEvent<
      PlatformInitializedEvent.InputTuple,
      PlatformInitializedEvent.OutputTuple,
      PlatformInitializedEvent.OutputObject
    >;
  };
}
